### ISSUE TITLE
Change rarity 

### ISSUE THREAD

**Issue by TheKuwagata** [TokyoSU/CustomRarityMod#1]
Hello. Your mod is awesome. but I would like to suggest making the epic rarity purple and changing the border colors to match the colors of the rarities
![image](https://github.com/TokyoSU/CustomRarityMod/assets/96778859/7384ff5e-ca38-47e3-9b89-c815dccb6d9e)

**Comment by TokyoSU** [comment]
@coppalka If you want purple color, choose the unique rarity :) , or do you want the epic rarity to be purple because of the one in minecraft ?

**Comment by TokyoSU** [comment]
I'm using the rarity color from the MMORPG Grand Fantasia which are not the same as minecraft, maybe this could be confusing.

**Comment by TokyoSU** [comment]
Oh right i could invert unique and epic color so it wont confuse anymore.
Will do tomorrow :)

**Comment by TheKuwagata** [comment]
> @coppalka If you want purple color, choose the unique rarity :) , or do you want the epic rarity to be purple because of the one in minecraft ?

if you have your own idea, then I don’t dare argue)

**Comment by TheKuwagata** [comment]
> Oh right i could invert unique and epic color so it wont confuse anymore. Will do tomorrow :)

its will be good

**Comment by TokyoSU** [comment]
@coppalka done in the version 1.0.2, update the resourcepack too.

**Comment by TokyoSU** [comment]
If it's still not right, you can reopen this issue 👍
